use_frameworks!

target 'UIFastTableView_Example' do
  pod 'UIFastTableView', :path => '../'

  target 'UIFastTableView_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
